#!/bin/bash

#######################################################################
# Azure Service Bus Provisioning Script
# Creates the necessary Azure resources for the tracing demo
#######################################################################

set -e

# Configuration - modify these as needed
RESOURCE_GROUP="${RESOURCE_GROUP:-tracing-demo-rg}"
LOCATION="${LOCATION:-uksouth}"
SERVICE_BUS_NAMESPACE="${SERVICE_BUS_NAMESPACE:-tracing-demo-sb-$(date +%s)}"
QUEUE_NAME="${QUEUE_NAME:-trade-messages}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}Azure Service Bus Provisioning Script${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo -e "${YELLOW}Note: You can skip this script and use the local Service Bus Emulator instead.${NC}"
echo -e "${YELLOW}      Set USE_SERVICE_BUS_EMULATOR=true to use the emulator.${NC}"
echo ""
echo "Configuration:"
echo "  Resource Group:      $RESOURCE_GROUP"
echo "  Location:            $LOCATION"
echo "  Service Bus NS:      $SERVICE_BUS_NAMESPACE"
echo "  Queue Name:          $QUEUE_NAME"
echo ""

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI is not installed.${NC}"
    echo "Please install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if logged in to Azure
echo -e "${YELLOW}Checking Azure login status...${NC}"
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in. Initiating login...${NC}"
    az login
fi

# Display current subscription
SUBSCRIPTION=$(az account show --query name -o tsv)
echo -e "${GREEN}Using subscription: $SUBSCRIPTION${NC}"
echo ""

# Create Resource Group
echo -e "${YELLOW}Creating Resource Group: $RESOURCE_GROUP...${NC}"
az group create \
    --name "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --output none
echo -e "${GREEN}✓ Resource Group created${NC}"

# Create Service Bus Namespace
echo -e "${YELLOW}Creating Service Bus Namespace: $SERVICE_BUS_NAMESPACE...${NC}"
echo "  (This may take a few minutes...)"
az servicebus namespace create \
    --name "$SERVICE_BUS_NAMESPACE" \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --sku Standard \
    --output none
echo -e "${GREEN}✓ Service Bus Namespace created${NC}"

# Create Queue
echo -e "${YELLOW}Creating Queue: $QUEUE_NAME...${NC}"
az servicebus queue create \
    --name "$QUEUE_NAME" \
    --namespace-name "$SERVICE_BUS_NAMESPACE" \
    --resource-group "$RESOURCE_GROUP" \
    --max-size 1024 \
    --default-message-time-to-live P14D \
    --lock-duration PT1M \
    --max-delivery-count 10 \
    --enable-partitioning false \
    --output none
echo -e "${GREEN}✓ Queue created${NC}"

# Get connection string
echo -e "${YELLOW}Retrieving connection string...${NC}"
CONNECTION_STRING=$(az servicebus namespace authorization-rule keys list \
    --name RootManageSharedAccessKey \
    --namespace-name "$SERVICE_BUS_NAMESPACE" \
    --resource-group "$RESOURCE_GROUP" \
    --query primaryConnectionString \
    --output tsv)

# Create .env file
ENV_FILE=".env"
echo -e "${YELLOW}Creating $ENV_FILE file...${NC}"
cat > "$ENV_FILE" << EOF
# Azure Service Bus Configuration
# Generated by provision-azure.sh on $(date)

AZURE_SERVICE_BUS_CONNECTION_STRING=$CONNECTION_STRING
AZURE_SERVICE_BUS_QUEUE_NAME=$QUEUE_NAME

# Azure Resource Information
AZURE_RESOURCE_GROUP=$RESOURCE_GROUP
AZURE_SERVICE_BUS_NAMESPACE=$SERVICE_BUS_NAMESPACE
AZURE_LOCATION=$LOCATION

# Grafana Cloud Configuration
# Get these from Grafana Cloud > Connections > OpenTelemetry (OTLP)
GRAFANA_CLOUD_OTLP_ENDPOINT=https://otlp-gateway-prod-us-central-0.grafana.net/otlp
GRAFANA_CLOUD_INSTANCE_ID=<your-instance-id>
GRAFANA_CLOUD_API_KEY=<your-api-key>

# Service Bus Emulator (set to true to use local emulator instead of Azure)
USE_SERVICE_BUS_EMULATOR=false
SERVICE_BUS_EMULATOR_HOST=localhost
EOF
echo -e "${GREEN}✓ Environment file created: $ENV_FILE${NC}"

# Summary
echo ""
echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}Provisioning Complete!${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo "Resources created:"
echo "  • Resource Group:       $RESOURCE_GROUP"
echo "  • Service Bus Namespace: $SERVICE_BUS_NAMESPACE"
echo "  • Queue:                $QUEUE_NAME"
echo ""
echo -e "${YELLOW}Connection string saved to $ENV_FILE${NC}"
echo ""
echo "Next steps:"
echo "  1. Update Grafana Cloud credentials in .env:"
echo "     - GRAFANA_CLOUD_OTLP_ENDPOINT"
echo "     - GRAFANA_CLOUD_INSTANCE_ID"
echo "     - GRAFANA_CLOUD_API_KEY"
echo ""
echo "  2. Load the environment variables:"
echo "     export \$(cat .env | xargs)"
echo ""
echo "  3. Start the OTel Collector:"
echo "     docker compose up otel-collector -d"
echo ""
echo "  4. Run the services locally:"
echo "     dotnet run --project src/TradeService"
echo "     dotnet run --project src/SettlementService"
echo ""
echo "  5. Or use Docker Compose for everything:"
echo "     docker compose up"
echo ""
echo -e "${YELLOW}Note: Keep the .env file secure and do not commit it to source control.${NC}"
echo ""
echo -e "${YELLOW}IMPORTANT: Update the Grafana Cloud credentials in .env before running the services.${NC}"

